# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_service_pb2 as grpc__service__pb2


class DAMAStub(object):
    """The DAMA service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.bid_server = channel.unary_unary(
                '/grpc_service.DAMA/bid_server',
                request_serializer=grpc__service__pb2.Bid.SerializeToString,
                response_deserializer=grpc__service__pb2.BiddingResult.FromString,
                )
        self.get_server_price = channel.unary_unary(
                '/grpc_service.DAMA/get_server_price',
                request_serializer=grpc__service__pb2.Connection.SerializeToString,
                response_deserializer=grpc__service__pb2.Price.FromString,
                )
        self.get_server_id = channel.unary_unary(
                '/grpc_service.DAMA/get_server_id',
                request_serializer=grpc__service__pb2.Connection.SerializeToString,
                response_deserializer=grpc__service__pb2.ServerID.FromString,
                )
        self.set_layers_assigned = channel.unary_unary(
                '/grpc_service.DAMA/set_layers_assigned',
                request_serializer=grpc__service__pb2.Assignment.SerializeToString,
                response_deserializer=grpc__service__pb2.ServerResponse.FromString,
                )
        self.start_discounting = channel.unary_unary(
                '/grpc_service.DAMA/start_discounting',
                request_serializer=grpc__service__pb2.Connection.SerializeToString,
                response_deserializer=grpc__service__pb2.Bid.FromString,
                )


class DAMAServicer(object):
    """The DAMA service definition.
    """

    def bid_server(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_server_price(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_server_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_layers_assigned(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start_discounting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DAMAServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'bid_server': grpc.unary_unary_rpc_method_handler(
                    servicer.bid_server,
                    request_deserializer=grpc__service__pb2.Bid.FromString,
                    response_serializer=grpc__service__pb2.BiddingResult.SerializeToString,
            ),
            'get_server_price': grpc.unary_unary_rpc_method_handler(
                    servicer.get_server_price,
                    request_deserializer=grpc__service__pb2.Connection.FromString,
                    response_serializer=grpc__service__pb2.Price.SerializeToString,
            ),
            'get_server_id': grpc.unary_unary_rpc_method_handler(
                    servicer.get_server_id,
                    request_deserializer=grpc__service__pb2.Connection.FromString,
                    response_serializer=grpc__service__pb2.ServerID.SerializeToString,
            ),
            'set_layers_assigned': grpc.unary_unary_rpc_method_handler(
                    servicer.set_layers_assigned,
                    request_deserializer=grpc__service__pb2.Assignment.FromString,
                    response_serializer=grpc__service__pb2.ServerResponse.SerializeToString,
            ),
            'start_discounting': grpc.unary_unary_rpc_method_handler(
                    servicer.start_discounting,
                    request_deserializer=grpc__service__pb2.Connection.FromString,
                    response_serializer=grpc__service__pb2.Bid.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_service.DAMA', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DAMA(object):
    """The DAMA service definition.
    """

    @staticmethod
    def bid_server(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_service.DAMA/bid_server',
            grpc__service__pb2.Bid.SerializeToString,
            grpc__service__pb2.BiddingResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_server_price(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_service.DAMA/get_server_price',
            grpc__service__pb2.Connection.SerializeToString,
            grpc__service__pb2.Price.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_server_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_service.DAMA/get_server_id',
            grpc__service__pb2.Connection.SerializeToString,
            grpc__service__pb2.ServerID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def set_layers_assigned(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_service.DAMA/set_layers_assigned',
            grpc__service__pb2.Assignment.SerializeToString,
            grpc__service__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def start_discounting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_service.DAMA/start_discounting',
            grpc__service__pb2.Connection.SerializeToString,
            grpc__service__pb2.Bid.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
